name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose --target x86_64-pc-windows-msvc
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: rusty-twinkle-tray.exe
        path: target/x86_64-pc-windows-msvc/release/rusty-twinkle-tray.exe
